### ISSUE TITLE
cannot coerce class ‘"DirichletRegData"’ to a data.frame

### ISSUE THREAD

**Issue by vestlink** [maiermarco/DirichletReg#1]
Hi.

I get this error when following the tutorial:

```
dd <- range(ArcticLake$depth)
X <- data.frame(depth = seq(dd[1], dd[2], length.out = 200))
pp <- predict(DirichReg(AL ~ depth + I(depth^2), AL), X)
```

```
> pp <- predict(DirichReg(AL ~ depth + I(depth^2), AL), X)
Error in as.data.frame.default(data, optional = TRUE) : 
  cannot coerce class ‘"DirichletRegData"’ to a data.frame
```

**Comment by maiermarco** [comment]
Hi, which versions of R and DirichletReg did you use? (Works with R 4.0.0 and DirichletReg 0.7.0 from CRAN.)

**Comment by vestlink** [comment]
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DirichletReg_0.7-0 Formula_1.2-3     

loaded via a namespace (and not attached):
 [1] zoo_1.8-8        compiler_4.0.0   miscTools_0.6-26 sandwich_2.5-1   tools_4.0.0      tinytex_0.23    
 [7] maxLik_1.3-8     grid_4.0.0       digest_0.6.25    xfun_0.14        lattice_0.20-41

**Comment by vestlink** [comment]
Maybe a MAC-issue?

**Comment by vestlink** [comment]
I did just this part from scratch. It worked. I think it could be due to manipulation to the AL-variable earlier in the Vignette-tutorial...

**Comment by maiermarco** [comment]
> I did just this part from scratch. It worked. I think it could be due to manipulation to the AL-variable earlier in the Vignette-tutorial...

Thanks for the update. Do you mean manipulation of the data by code inside the vignette or did you alter it?

**Comment by vestlink** [comment]
I was only manipulating the code according to the vignette

**Comment by maiermarco** [comment]
Ok, I'm going to close this for now.

If you experience any further issues, you can export and append the command history per

```{r}
savehistory(file = "my_command_history.Rhistory")
```

so I can reproduce any errors.
