### ISSUE TITLE
Suppressing the output of summary()

### ISSUE THREAD

**Issue by gokceneraslan** [maiermarco/DirichletReg#3]
It'd be great to have an elegant way of suppressing the output of the `summary.DirichletRegModel()` function, I think (https://github.com/maiermarco/DirichletReg/blob/master/R/summary.DirichletRegModel.R#L39) (other than the `sink()` magic).

**Comment by maiermarco** [comment]
Hi @gokceneraslan, thanks for pointing that out. I just uploaded a pre-release of the new version where `summary`-functions return the object without printing it.
(If you have the tools to build packages, you can install it directly using `devtools::install_github("maiermarco/DirichletReg")`).
