### ISSUE TITLE
Coercing the results of summary() on DirichletRegModel object

### ISSUE THREAD

**Issue by travis-m-blimkie** [maiermarco/DirichletReg#5]
Hello!

I was wondering if there's a simple, built-in way to convert the output of `summary(dr_result)` to a data frame or matrix, which keeps all the beta-coefficients and the variable names of each section.

For example, starting with a summary object like:
```r
library(DirichletReg)
library(tidyverse)

head(ArcticLake)
AL <- DR_data(ArcticLake[, 1:3])

lake1 <- DirichReg(AL ~ depth, ArcticLake)

summary(lake1)
```
```
Call:
DirichReg(formula = AL ~ depth, data = ArcticLake)

Standardized Residuals:
          Min       1Q   Median      3Q     Max
sand  -1.7724  -0.8319   0.0120  1.3435  2.2862
silt  -1.0863  -0.5343  -0.1279  0.2892  1.4493
clay  -2.0868  -0.7516  -0.0012  0.4391  1.9660

------------------------------------------------------------------
Beta-Coefficients for variable no. 1: sand
            Estimate Std. Error z value Pr(>|z|)   
(Intercept) 0.116625   0.409292   0.285  0.77569   
depth       0.023351   0.007454   3.133  0.00173 **
------------------------------------------------------------------
Beta-Coefficients for variable no. 2: silt
             Estimate Std. Error z value Pr(>|z|)    
(Intercept) -0.310596   0.344731  -0.901    0.368    
depth        0.055567   0.006365   8.730   <2e-16 ***
------------------------------------------------------------------
Beta-Coefficients for variable no. 3: clay
             Estimate Std. Error z value Pr(>|z|)    
(Intercept) -1.151956   0.298473   -3.86 0.000114 ***
depth        0.064302   0.005738   11.21  < 2e-16 ***
------------------------------------------------------------------
Significance codes: 0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Log-likelihood: 101.4 on 6 df (100 BFGS + 1 NR Iterations)
AIC: -190.7, BIC: -180.8
Number of Observations: 39
Link: Log
Parametrization: common
```

I would like the results in a data frame that looks something like:
| Term             | Estimate    | Std. Error  | z value    | Pr_z         |
|:-----------------|:------------|:------------|:-----------|:-------------|
| sand:(Intercept) | 0.11662480  | 0.409291821 | 0.2849429  | 7.756879e-01 |
| sand:depth       | 0.02335114  | 0.007453915 | 3.1327352  | 1.731856e-03 |
| silt:(Intercept) | -0.31059591 | 0.344731381 | -0.9009795 | 3.675992e-01 |
| silt:depth       | 0.05556745  | 0.006365298 | 8.7297490  | 2.552384e-18 |
| clay:(Intercept) | -1.15195642 | 0.298472772 | -3.8595025 | 1.136181e-04 |
| clay:depth       | 0.06430175  | 0.005738180 | 11.2059480 | 3.812503e-29 |

I managed to put together a solution using the following, but was wondering if there was an easier/more streamlined way of accomplishing this:
```r
# Create the initial data frame to hold results - rownames are not specific or indicative of the variable (sand, silt, etc.)
lake1_matrix <- lake1 %>%
  summary() %>%
  unclass() %>%
  pluck("coef.mat") %>%
  as.data.frame()

# Use the `coefficients` element, which does have the "proper" names of results
lake1_names <- lake1 %>%
  summary() %>%
  unclass() %>%
  pluck("coefficients") %>%
  names()

rownames(lake1_matrix) <- lake1_names
```

Any help would be much appreciated. 

Cheers!

**Comment by maiermarco** [comment]
Hi Travis,

thank you for your question and the example code.

As a quick workaround, you could include this function that extracts the coefficients, labels them correctly and returns a `data.frame` (with or without stars indicating the significance levels):

## Function

```r
DR_summary_df <- function(x, p_val_stars = FALSE){
  smmry_x <- summary(x)
  coefmat <- as.data.frame(smmry_x$coef.mat, check.names=FALSE)
  rownames(coefmat) <- names(x$coefficients)

  if(!p_val_stars) return(coefmat) else {
    p_stars <- symnum(x = coefmat[,4L], corr = FALSE, na = FALSE,
      cutpoints = c(0, .001, .01, .05, .1, 1),
      symbols = c("***", "**", "*", ".", " ")
    )
    return(cbind(coefmat, "p_st" = p_stars))
  }
}
```

## Default behavior without stars

```r
DR_summary_df(lake1)
```

```
                    Estimate  Std. Error    z value     Pr(>|z|)
sand:(Intercept)  0.11662480 0.409291821  0.2849429 7.756879e-01
sand:depth        0.02335114 0.007453915  3.1327352 1.731856e-03
silt:(Intercept) -0.31059591 0.344731381 -0.9009795 3.675992e-01
silt:depth        0.05556745 0.006365298  8.7297490 2.552384e-18
clay:(Intercept) -1.15195642 0.298472772 -3.8595025 1.136181e-04
clay:depth        0.06430175 0.005738180 11.2059480 3.812503e-29
```

## With stars

```r
DR_summary_df(lake1, p_val_stars = TRUE)
```

```
                    Estimate  Std. Error    z value     Pr(>|z|) p_st
sand:(Intercept)  0.11662480 0.409291821  0.2849429 7.756879e-01     
sand:depth        0.02335114 0.007453915  3.1327352 1.731856e-03   **
silt:(Intercept) -0.31059591 0.344731381 -0.9009795 3.675992e-01     
silt:depth        0.05556745 0.006365298  8.7297490 2.552384e-18  ***
clay:(Intercept) -1.15195642 0.298472772 -3.8595025 1.136181e-04  ***
clay:depth        0.06430175 0.005738180 11.2059480 3.812503e-29  ***
```

## Markdown compatibility

The `kable` function from the `knitr` package works:

```r
knitr::kable(DR_summary_df(lake1, p_val_stars = TRUE))
```


|                 |   Estimate| Std. Error|    z value| Pr(>&#124;z&#124;)|p_st |
|:----------------|----------:|----------:|----------:|------------------:|:----|
|sand:(Intercept) |  0.1166248|  0.4092918|  0.2849429|          0.7756879|     |
|sand:depth       |  0.0233511|  0.0074539|  3.1327352|          0.0017319|**   |
|silt:(Intercept) | -0.3105959|  0.3447314| -0.9009795|          0.3675992|     |
|silt:depth       |  0.0555675|  0.0063653|  8.7297490|          0.0000000|***  |
|clay:(Intercept) | -1.1519564|  0.2984728| -3.8595025|          0.0001136|***  |
|clay:depth       |  0.0643018|  0.0057382| 11.2059480|          0.0000000|***  |

--------

Hope this helps for now, I will keep that in mind and see if I can include it somewhere to work out of the box.

**Comment by travis-m-blimkie** [comment]
That's perfect, thanks for the quick and thorough response!

Cheers!
